<html>
<head>
<title>Email Call Search Result</title>    
<?php 
include('config.php');
include_once('utility.php');
include_once('parameter.php');
include_once('auditTrial.php');
include_once('callData.php');
include_once('email.php');
session_start();
include('layoutjscss.php');
?>      
</head>
<body>
	<div class="ui-layout-center">
	<?php
	$groupID = $_SESSION['s_loginGroupid'];
	if (isset($groupID)) {
		if ($groupID<=1) { // only supervisor or admin group can have email function 
			if($_SERVER["REQUEST_METHOD"] == "GET") {
				$action = addslashes($_GET['action']);
				if ($action=="dispResult") {
					echo $_SESSION['s_systemMessage'];
					unset($_SESSION['s_systemMessage']);
					// the form
					$form = "
					<meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\">
					<link rel=\"stylesheet\" href=\"libs/css/astlogger.css\">
					<form action=\"callSearchEmailResult.php\" method=\"post\">
					<table>
					<tr>
					<td ><input name=\"formname\" type=\"hidden\" id=\"formname\" value=\"callSearchEmailSent\"></td>
					</tr>
					<tr>
					<td><input type=\"submit\" value=\"  OK  \"></td>
					</tr>
					</table>
					</form>
					";
					echo $form;
				} else {
					// retrieve the email address of the user
					$emailSender = getParameter("al_emailsenderaddress");
					if (strlen($emailSender)) {
						$emailTo = $_SESSION['s_loginEmail'];
						$fullname = $_SESSION['s_loginFullname'];
						if (strlen($emailTo)) {
							$getKey = addslashes($_GET['key']);
							// format the url
							$url = curPageDir();
							$url .= "callSearchResult.php?key=";
							$url .= $getKey;
							// format the message
							$message  = "Hi,\r\n";
							$message .= "\r\n";
							$message .= "$fullname sends you a voice call URL, the link is follow:\r\n";
							$message .= "\r\n";
							$message .= "$url\r\n";
							$message .= "\r\n";
							$message .= "Please do not reply this email, it was generated by AstLogger Web.\r\n";
							// the form
							$recpath = recPath($getKey);
							$pos = strrpos($recpath, "/");
							$filename = substr($recpath, $pos+1);							
							$form = "
							<meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\">
							<link rel=\"stylesheet\" href=\"libs/css/astlogger.css\">
							<form action=\"callSearchEmailResult.php\" method=\"post\">
							<table width=\"100%\">
							<tr>
							<td>From</td>
							<td>:</td>
							<td >$emailSender</td>
							</tr>
							<tr>
							<td>To</td>
							<td>:</td>
							<td><textarea name=\"emailTo\" id=\"emailTo\" rows=\"1\" cols=\"80\" >$emailTo</textarea></td>
							</tr>
							<tr>
							<td>Cc</td>
							<td>:</td>
							<td><textarea name=\"emailCc\" id=\"emailCc\" rows=\"1\" cols=\"80\" ></textarea></td>
							</tr>						
							<tr>
							<td>Subject</td>
							<td>:</td>
							<td><textarea name=\"emailSubject\" id=\"emailSubject\" rows=\"1\" cols=\"80\" >Call Record $getKey</textarea></td>
							</tr>						
							<tr>
							<td>Attachment</td>
							<td>:</td>
							<td><input name=\"emailAttachment\" id=\"emailAttachment\" type=\"checkbox\" value=\"yes\" >$filename</td>
							</tr>						
							<tr>
							<td></td>
							<td></td>
							<td><textarea name=\"emailContent\" id=\"emailContent\" rows=\"20\" cols=\"80\" >$message</textarea></td>
							</tr>
							<tr>
							<td ><input name=\"formname\" type=\"hidden\" id=\"formname\" value=\"callSearchEmailForm\"></td>
							</tr>
							<tr>
							<td ><input name=\"key\" type=\"hidden\" id=\"key\" value=\"$getKey\"></td>
							</tr>
							<tr>
							<td></td>
							<td></td>
							<td><input type=\"submit\" value=\"  Submit  \"></td>
							</tr>
							</table>
							</form>
							";
							echo $form;
						} else {
							echo "Error: the user without email address configured.";
						}
					} else {
						echo "System email address is not set, please contact system administrator.";
					}
				}
			} else if ($_SERVER["REQUEST_METHOD"] == "POST") {		
				$formname=addslashes($_POST['formname']);
				if ($formname=="callSearchEmailSent") {
					$urlPage = $_SESSION['s_loginDestination'];
					unset($_SESSION['s_loginDestination']);
					if (isset($urlPage)) {
						header("location: $urlPage");
					} else {
						header("location: callSearchResult.php");
					}
				} else if ($formname=="callSearchEmailForm") {	
					$emailSender = getParameter("al_emailsenderaddress");
					$emailSenderDisplayName = "AstLogger Web";						
					$emailTo = addslashes($_POST['emailTo']);
					$emailCc = addslashes($_POST['emailCc']);
					$emailSubject = addslashes($_POST['emailSubject']);
					$emailAttachment = addslashes($_POST['emailAttachment']);
					$message = addslashes($_POST['emailContent']);
					$key = addslashes($_POST['key']); 
					if (strlen($emailTo)) {	
						if ($emailAttachment=="yes") {
							$recpathArray = recpathArray($key);
							if (sizeof($recpathArray)>0) {
								$pos = strrpos($recpathArray[0], "/");
								$filename = substr($recpathArray[0], $pos+1);
								$dispfilename = $recpathArray[3];
								$path =  substr($recpathArray[0], 0, $pos+1);
								$applicationFolder = getParameter("al_applicationfolder");
								$fullpath = $_SERVER['DOCUMENT_ROOT']."/$applicationFolder".$path;
								if (mail_attachment($filename, $fullpath, $dispfilename, $emailTo, $emailCc, $emailSender, $emailSenderDisplayName,
										$emailSender, $emailSubject, $message)==true) {
									$_SESSION['s_systemMessage'] = "Email call search result to $emailTo $emailCc successfully.";
									// audit trial
									$auditTrial = "email call search result key($key) to $emailTo $emailCc successfully.";
									insertAuditTrial($auditTrial);
								} else {
									$_SESSION['s_systemMessage'] = "Email call search result to $emailTo $emailCc failed.";
									// audit trial
									$auditTrial = "email call search result key($key) to $emailTo $emailCc failed.";
									insertAuditTrial($auditTrial);
								}
								if ($recpathArray[2]=="true") {
									unlink($recpathArray[0]);
								}
							} else {
								$_SESSION['s_systemMessage'] = "Prepare record file for email call search result to $emailTo $emailCc failed.";
								// audit trial
								$auditTrial = "prepare record file for email call search result key($key) to $emailTo $emailCc failed.";
								insertAuditTrial($auditTrial);
							}						
						} else {
							if (mail_only($emailTo, $emailCc, $emailSender, $emailSenderDisplayName,
									$emailSender, $emailSubject, $message)==true) {
								$_SESSION['s_systemMessage'] = "Email call search result to $emailTo $emailCc successfully.";
								// audit trial
								$auditTrial = "email call search result key($key) to $emailTo $emailCc successfully.";
								insertAuditTrial($auditTrial);
							} else {
								$_SESSION['s_systemMessage'] = "Email call search result to $emailTo $emailCc failed.";
								// audit trial
								$auditTrial = "email call search result key($key) to $emailTo $emailCc failed.";
								insertAuditTrial($auditTrial);
							}						
						}	
					}
					header("location: callSearchEmailResult.php?action=dispResult");
				}
			} // $_SERVER
		} // if ($groupID<=1)
	} // if (isset($groupID))
	?>		
	</div>
	<div class="ui-layout-north"> 
	<?php
		include('header.php'); 
	?>
	</div>     
    <div class="ui-layout-west">
	<?php
		include('callSearchForm.php');
	?>    
	</div>  	
</body>
</html>



